name: sharecalendar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core:
  firebase_auth:
  firebase_database:
  shared_preferences: ^2.0.17
  uuid: ^3.0.7
  collection: ^1.17.0

  # 새로 추가된 패키지
  flutter_colorpicker: 1.1.0  # 최신 버전 사용

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets 및 fonts 섹션은 필요에 따라 주석 해제하여 사용
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic